language: python

dist: xenial
sudo: yes
python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python webserver.py --debug &

script:
  - python isthehubup.py --once
  - curl -f http://localhost:5000/
